---
# defaults for acs-spokes-sensor-setup role

rox_central_address: ""
rox_api_token: ""
openshift_version: "4"
roxctl_insecure: true
sensor_work_dir: "/root/secured_clusters"
force_sensor_regeneration: false
cleanup_sensor_generation: false
