apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: assisted-service-cpu-memory
  name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    storageClassName: {{ agentservice_sc }}
    resources:
      requests:
        storage: 20Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    storageClassName: {{ agentservice_sc }}
    resources:
      requests:
        storage: 100Gi
  mirrorRegistryRef:
    name: "assisted-mirror-config"
  osImages:
{% for os_image in mce_os_images %}
  - openshiftVersion: "{{ os_image.openshiftVersion }}"
    version: "{{ os_image.version }}"
    url: "{{ os_image.url }}"
    rootFSUrl: "{{ os_image.rootFSUrl }}"
    cpuArchitecture: x86_64
{% endfor %}
