---
# ibi-install-prep default vars

# This should be your bastion machine
http_store_host: "{{ groups['bastion'][0] }}"
http_store_port: 8081

# SNO to prepare, data is sourced from jetlag inventory file
# Ideal to use VM hosted on NVMe for disk speed
hv_vm_target: vm00005

# Default BMC port for sushy emulator is 9000
redfish_bmc_port: 9000

# Default sushy emulator user/password
redfish_user: redhat
redfish_password: password

# Version of the seed image was used during the prep iso creation
seed_image_version: 4.19.14
