---
# ibi-install-prep default vars

# This should be your bastion machine
http_store_host: "{{ groups['bastion'][0] }}"
http_store_port: 8081

# SNO to prepare, data is sourced from jetlag inventory file
hv_vm_target: vm00006

# Default BMC port for sushy emulator is 9000
redfish_bmc_port: 9000

# Default sushy emulator user/password
redfish_user: redhat
redfish_password: password
