---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "group-du-3node-latest"
  namespace: "ztp-group"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    group-du-3node: ""
    # du-profile: "latest"
  # Because 3-node clusters are both workers and masters, and the MCP pool for master binds more strongly than that for worker,
  # the Performance Profile needs to be set up to apply to the master MCP:
  mcp: "master"
  sourceFiles:
    - fileName: PtpConfigSlave.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
      policyName: "{{ 'ptp-config' if manyPolicies else 'config' }}-policy"
      metadata:
        name: "du-ptp-slave"
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
        annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
          scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
          scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
          site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
          site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
{% endif +%}
      spec:
        profile:
        - name: "slave"
          # This interface must match the hardware in this group
          interface: "ens5f0"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
    - fileName: SriovOperatorConfig.yaml
      policyName: "{{ 'sriov-config' if manyPolicies else 'config' }}-policy"
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
      metadata:
        annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
          scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
          scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
          site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
          site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
{% endif +%}
{% if setup_ztp_enable_performanceprofile %}
    - fileName: PerformanceProfile.yaml
      policyName: "{{ 'tuning-config' if manyPolicies else 'config' }}-policy"
      spec:
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: "2-19,22-39"
          reserved: "0-1,20-21"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
    - fileName: TunedPerformancePatch.yaml
      policyName: "{{ 'tuning-config' if manyPolicies else 'config' }}-policy"
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
      metadata:
        annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
          scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
          scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
          site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
          site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
{% endif +%}
{% else %}
#     - fileName: PerformanceProfile.yaml
#       policyName: "{{ 'tuning-config' if manyPolicies else 'config' }}-policy"
#       spec:
#         cpu:
#           # These must be tailored for the specific hardware platform
#           isolated: "2-19,22-39"
#           reserved: "0-1,20-21"
#         hugepages:
#           defaultHugepagesSize: 1G
#           pages:
#             - size: 1G
#               count: 32
#     - fileName: TunedPerformancePatch.yaml
#       policyName: "{{ 'tuning-config' if manyPolicies else 'config' }}-policy"
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
#      metadata:
#        annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
#          scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
#          scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
#          site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
#          site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
{% endif +%}
{% endif %}
    #
    # These CRs are to enable crun on master and worker nodes for 4.13+ only
    #
    # Include these CRs in the group PGT instead of the common PGT to make sure
    # they are applied after the operators have been successfully installed,
    # however, it's strongly recommended to include these CRs as day-0 extra manifests
    # to avoid the risky of an extra reboot.
    - fileName: optional-extra-manifest/enable-crun-master.yaml
      policyName: "config-policy"
{% if manyPolicies %}
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
{% endif %}
    - fileName: optional-extra-manifest/enable-crun-worker.yaml
      policyName: "config-policy"
{% if manyPolicies %}
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
{% endif %}
    #
    # NMState operator is used for IPsec configuration with NMState
    # - fileName: NMStateSubscriptionNS.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: NMStateSubscriptionOperGroup.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: NMStateSubscription.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: NMStateOperatorStatus.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: NMState.yaml
    #   policyName: "subscriptions-policy"
