---
# aap-deploy default vars

automationcontroller_postgres_storage_class: localstorage-sc

aap_database_postgres_storage_class: localstorage-sc

automationhub_file_storage_storage_class: localstorage-sc
automationhub_postgres_storage_class: localstorage-sc
automationhub_redis_storage_class: localstorage-sc

# Set the EDA URL to the expected automation controller route
eda_automationcontroller_url: automationcontroller-ansible-automation-platform.apps.example.com
