---
# mce-add-clusterimagesets tasks

- name: Clean directory with ClusterImageSets
  file:
    path: "{{ install_directory }}/mce-clusterimageset"
    state: absent

- name: Create directory for ClusterImageSets
  file:
    path: "{{ install_directory }}/mce-clusterimageset"
    state: directory

- name: Template out ClusterImageSets for MCE
  template:
    src: cis.yaml.j2
    dest: "{{ install_directory }}/mce-clusterimageset/{{ item.name }}-cis.yaml"
  with_items: "{{ mce_clusterimagesets }}"

- name: Apply ClusterImageSets to RHACM Hub Cluster
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc apply -f {{ install_directory }}/mce-clusterimageset
