---
# http-upgrade-graphs task

- name: Create directory for upgrade graphs
  file:
    path: "{{ http_store_path }}/data/upgrade"
    state: directory

# View upgrade graphs
# https://access.redhat.com/labs/ocpupgradegraph
# https://ctron.github.io/openshift-update-graph/#fast-4.15
- name: Download upgrade graphs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ http_store_path }}/data/upgrade/{{ item.name }}"
  loop:
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.14
    name: upgrade-graph_stable-4.14
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.15
    name: upgrade-graph_stable-4.15
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.16
    name: upgrade-graph_stable-4.16

  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.14
    name: upgrade-graph_fast-4.14
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.15
    name: upgrade-graph_fast-4.15
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.16
    name: upgrade-graph_fast-4.16

  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.15
    name: upgrade-graph_candidate-4.15
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.16
    name: upgrade-graph_candidate-4.16
