fields:
- id: ca_cert     
  type: string     
  label: ca certificate     
  help_text: The Certificate file for the CA    
  multiline: true   
- id: client_cert     
  type: string     
  label: client certificate     
  help_text: The Certificate file for the client     
  multiline: true   
- id: client_key     
  type: string     
  label: client Key     
  secret: true     
  help_text: The key file for the client     
  multiline: true   
- id: host
  type: string
  label: broker URL     
  help_text: Location of the Kafka broker