---
# rhacm-ztp-platform-upgrade-setup tasks

- name: Create directories for rhacm-ztp
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ http_store_path }}/data/upgrade"
  - "{{ install_directory }}/rhacm-ztp"
  - "{{ install_directory }}/rhacm-ztp/upgrade"

# View Upgrade graphs
# https://access.redhat.com/labs/ocpupgradegraph
# Also https://ctron.github.io/openshift-update-graph/#stable-4.12
- name: Download upgrade graphs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ http_store_path }}/data/upgrade/{{ item.name }}"
  loop:
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.9
    name: upgrade-graph_stable-4.9
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.10
    name: upgrade-graph_stable-4.10
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.11
    name: upgrade-graph_stable-4.11
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.12
    name: upgrade-graph_stable-4.12
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.13
    name: upgrade-graph_stable-4.13
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.10
    name: upgrade-graph_fast-4.10
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.11
    name: upgrade-graph_fast-4.11
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.12
    name: upgrade-graph_fast-4.12
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.13
    name: upgrade-graph_fast-4.13
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.14
    name: upgrade-graph_fast-4.14
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.15
    name: upgrade-graph_fast-4.15

- name: Get list of clusters for upgrade
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get managedclusters -l {{ clusters_label }} --no-headers -o custom-columns=NAME:'.metadata.name'
  register: ztp_done_clusters

- name: Template CGU object(s)
  template:
    src: cgu-platform-upgrade.yml.j2
    dest: "{{ install_directory }}/rhacm-ztp/upgrade/cgu-platform-upgrade-{{ du_upgrade_version | replace('.', '-') }}-{{ '%04d' | format(item) }}.yml"
  loop: "{{ range(((ztp_done_clusters.stdout_lines | length) / clusters_per_cgu) | round(0, 'ceil') | int) | list }}"

- name: Template CGU apply/patch scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0744"
  loop:
  - src: apply-cgu-platform.sh
    dest: "{{ install_directory }}/rhacm-ztp/upgrade/apply-cgu-platform-{{ du_upgrade_version | replace('.', '-') }}.sh"
  - src: patch-cgu-platform.sh
    dest: "{{ install_directory }}/rhacm-ztp/upgrade/patch-cgu-platform-{{ du_upgrade_version | replace('.', '-') }}.sh"

- name: Template the gen_checksum.sh script
  template:
    src: gen_checksum.sh
    dest: "{{ install_directory }}/rhacm-ztp/upgrade/gen_checksum.sh"
    mode: 0744

- name: Run the generate checksum script
  shell: |
    cd {{ install_directory }}/rhacm-ztp/upgrade
    {{ install_directory }}/rhacm-ztp/upgrade/gen_checksum.sh

- name: Get generate checksum script output
  slurp:
    src: "{{ install_directory }}/rhacm-ztp/upgrade/checksum-{{ du_upgrade_version }}.yaml"
  register: image_signature_data

- name: Template the platform upgrade PGT and admin-ack
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: du-upgrade.yaml.j2
    dest: "{{ install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/du-upgrade.yaml"
  - src: admin-ack.yaml
    dest: "{{ install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/source-crs/admin-ack.yaml"

- name: Enable platform upgrade PGT in the kustomization.yaml file
  replace:
    path: "{{ install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/kustomization.yaml"
    replace: "- du-upgrade.yaml"
    regexp: "# - du-upgrade.yaml"

- name: Commit and push the above changes to cnf-features-deploy
  shell: |
    cd {{ install_directory }}/rhacm-ztp/cnf-features-deploy
    git add ztp/gitops-subscriptions/argocd/cluster/ ztp/gitops-subscriptions/argocd/cluster-applications/
    git add ztp/gitops-subscriptions/argocd/policy/ ztp/gitops-subscriptions/argocd/policy-applications/
    git commit -a -m "Add Platform Upgrade PGT to {{ du_upgrade_version }}"
    git push origin-gogs
