---
# rhacm-ztp-ibu-setup tasks

- name: Create directories for IBU
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ install_directory }}/rhacm-ztp"
  - "{{ install_directory }}/rhacm-ztp/ibu"
  - "{{ install_directory }}/rhacm-ztp/ibu/scripts"

- name: Get list of clusters for upgrade
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get managedclusters -l {{ clusters_label }} --no-headers -o custom-columns=NAME:'.metadata.name' | grep -v local-cluster
  register: ztp_done_clusters

- name: Template the IBU PGT
  template:
    src: du-ibu.yaml.j2
    dest: "{{ install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/du-ibu.yaml"

- name: Enable IBU PGT in the kustomization.yaml file
  replace:
    path: "{{ install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/kustomization.yaml"
    replace: "- du-ibu.yaml"
    regexp: "# - du-ibu.yaml"

- name: Comment out OperatorHub.yaml source-cr because IBU requires 4.15 ztp site generator
  replace:
    path: /root/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/common-ranGen.yaml
    replace: |-
      # Start OPERATORHUB
          # - fileName: OperatorHub.yaml
          #   policyName: "config-policy"
      # End OPERATORHUB
    regexp: '^# Start OPERATORHUB[\s\S]*# End OPERATORHUB'
  when: ibu_seed_image_version is version('4.14.0', ">=")

- name: Apply catalogsource changes in the common-ranGen.yaml
  replace:
    path: "{{ install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/common-ranGen.yaml"
    replace: "{{ item.replace }}"
    regexp: "{{ item.regexp }}"
  loop:
  - replace: 'lca.openshift.io/target-ocp-version: "{{ ibu_seed_image_version }}"'
    regexp: 'lca.openshift.io/target-ocp-version: "[0-9.]*"'
  - replace: 'image: {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/{{ disconnected_operator_index_name }}:{{ operator_index_tag }}'
    regexp: 'image: {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/{{ disconnected_operator_index_name }}:v[0-9.\-a-zA-Z]*'

- name: Commit and push the above changes to cnf-features-deploy
  shell: |
    cd {{ install_directory }}/rhacm-ztp/cnf-features-deploy
    git add ztp/gitops-subscriptions/argocd/policy/
    git commit -a -m "Add IBU PGT to {{ ibu_seed_image_version }}"
    git push origin-gogs

- name: Trigger policy application policy-common-and-group for refresh
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc annotate applications.argoproj.io -n openshift-gitops policy-common-and-group argocd.argoproj.io/refresh=normal

- name: Template CGU ibu-prep object(s)
  template:
    src: cgu-ibu-prep.yml.j2
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/cgu-ibu-prep-{{ ibu_seed_image_version | replace('.', '-') }}-{{ '%04d' | format(item) }}.yml"
  loop: "{{ range(((ztp_done_clusters.stdout_lines | length) / ibu_prep_clusters_per_cgu) | round(0, 'ceil') | int) | list }}"

- name: Template CGU ibu-upgrade object(s)
  template:
    src: cgu-ibu-upgrade.yml.j2
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/cgu-ibu-upgrade-{{ ibu_seed_image_version | replace('.', '-') }}-{{ '%04d' | format(item) }}.yml"
  loop: "{{ range(((ztp_done_clusters.stdout_lines | length) / ibu_upgrade_clusters_per_cgu) | round(0, 'ceil') | int) | list }}"

- name: Template CGU ibu-rollback object(s)
  template:
    src: cgu-ibu-rollback.yml.j2
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/cgu-ibu-rollback-{{ ibu_seed_image_version | replace('.', '-') }}-{{ '%04d' | format(item) }}.yml"
  loop: "{{ range(((ztp_done_clusters.stdout_lines | length) / ibu_rollback_clusters_per_cgu) | round(0, 'ceil') | int) | list }}"

- name: Template CGU ibu-finalize object(s)
  template:
    src: cgu-ibu-finalize.yml.j2
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/cgu-ibu-finalize-{{ ibu_seed_image_version | replace('.', '-') }}-{{ '%04d' | format(item) }}.yml"
  loop: "{{ range(((ztp_done_clusters.stdout_lines | length) / ibu_finalize_clusters_per_cgu) | round(0, 'ceil') | int) | list }}"

- name: Template CGU apply scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0744"
  loop:
  - src: apply-cgu-ibu-prep.sh
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/apply-cgu-ibu-prep-{{ ibu_seed_image_version | replace('.', '-') }}.sh"
  - src: apply-cgu-ibu-upgrade.sh
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/apply-cgu-ibu-upgrade-{{ ibu_seed_image_version | replace('.', '-') }}.sh"
  - src: apply-cgu-ibu-rollback.sh
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/apply-cgu-ibu-rollback-{{ ibu_seed_image_version | replace('.', '-') }}.sh"
  - src: apply-cgu-ibu-finalize.sh
    dest: "{{ install_directory }}/rhacm-ztp/ibu/scripts/apply-cgu-ibu-finalize-{{ ibu_seed_image_version | replace('.', '-') }}.sh"
