apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: common-latest
placementBindingDefaults:
  name: common-placement-binding
policyDefaults:
  # categories: []
  #controls:
  #  - PR.DS-1 Data-at-rest
  namespace: ztp-common
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    labelSelector:
      common: "true"
  remediationAction: inform
  severity: low
  # standards: []
  namespaceSelector:
    exclude:
      - kube-*
    include:
      - '*'
  evaluationInterval:
    compliant: 10m
    noncompliant: 10s
policies:
{% if manyPolicies %}
- name: common-latest-sriov-subs-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
{% include "common/sriov-sub.yaml" %}
- name: common-latest-ptp-subs-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
{% include "common/ptp-sub.yaml" %}
- name: common-latest-log-subs-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
{% include "common/clo-sub.yaml" %}
- name: common-latest-storage-subs-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
{% include "common/storage-sub.yaml" %}
{% if include_lca_operator %}
- name: common-latest-lca-subs-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
{% include "common/lca-sub.yaml" %}
{% endif %}
{% if include_oadp_operator %}
- name: common-latest-oadp-subs-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
{% include "common/oadp-sub.yaml" %}
{% endif %}
- name: common-latest-monitoring-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "1"
  manifests:
    - path: source-crs/ReduceMonitoringFootprint.yaml
{% else %}
- name: common-latest-subscriptions-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
{% include "common/clo-sub.yaml" %}
    # Ptp operator
{% include "common/ptp-sub.yaml" %}
    # SRIOV operator
{% include "common/sriov-sub.yaml" %}
    # Storage operator
{% include "common/storage-sub.yaml" %}
    # LCA operator is used for orchestrating Image Based Upgrade for SNO
{% if include_lca_operator %}
{% include "common/lca-sub.yaml" %}
{% endif %}
    # OADP operator is used for backing up and restoring application during Image Based Upgrade
{% if include_oadp_operator %}
{% include "common/oadp-sub.yaml" %}
{% endif %}
{% endif %}
- name: common-latest-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "1"
  manifests:
    - path: source-crs/ReduceMonitoringFootprint.yaml
{% if rhacm_disconnected_registry and rhacm_disconnected_registry|length > 1 %}
    - path: source-crs/DefaultCatsrc.yaml
      patches:
      - metadata:
          name: {{ common_catalogsource_name }}
{% if extraHubCommonTemplates %}
          annotations:
          {%- raw %}
            scale-test-label-1: '{{hub fromConfigMap "" "common-template-map" "key3" hub}}'
            scale-test-label-2: '{{hub fromConfigMap "" "common-template-map" "key4" hub}}'
          {%- endraw +%}
          labels:
            lca.openshift.io/target-ocp-version: "4.18.0"
{% endif %}
        spec:
          displayName: disconnected-redhat-operators
          image: {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/{{ disconnected_operator_index_name}}:{{ operator_index_tag }}
    - path: source-crs/DisconnectedICSP.yaml
      patches:
      - spec:
          repositoryDigestMirrors:
          - mirrors:
            - {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}
            source: registry.redhat.io
          - mirrors:
            - {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}
            source: brew.registry.redhat.io
          - mirrors:
            - {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}
            source: registry-proxy.engineering.redhat.com
          - mirrors:
            - {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/ocp4/openshift4
            source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
          - mirrors:
            - {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/ocp4/openshift4
            source: quay.io/openshift-release-dev/ocp-release
{% endif %}
