apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: group-du-sno-latest
placementBindingDefaults:
  name: group-du-sno-placement-binding
policyDefaults:
  # categories: []
  #controls:
  #  - PR.DS-1 Data-at-rest
  namespace: ztp-group
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    labelSelector:
      group-du-sno: ""
  remediationAction: inform
  severity: low
  # standards: []
  namespaceSelector:
    exclude:
      - kube-*
    include:
      - '*'
  evaluationInterval:
    compliant: 10m
    noncompliant: 10s
policies:
{% if manyPolicies %}
{% if include_oadp_operator %}
- name: group-du-sno-oadp-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% include "group-du/oadp-config.yaml" %}
{% endif %}
{% if include_lca_operator %}
- name: group-du-sno-lca-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% include "group-du/lca-config.yaml" %}
{% endif %}
- name: group-du-sno-olm-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% include "group-du/olm-config.yaml" %}
- name: group-du-sno-ptp-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% include "group-du/ptp-config.yaml" %}
- name: group-du-sno-sriov-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% include "group-du/sriov-operator-config-sno.yaml" %}
- name: group-du-sno-network-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% include "group-du/disable-sno-network-diag.yaml" %}
{% if setup_ztp_enable_performanceprofile %}
- name: group-du-sno-tuning-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% include "group-du/performance-profile-sno.yaml" %}
{% endif %}
{% else %}
- name: group-du-sno-latest-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
{% if include_oadp_operator %}
{% include "group-du/oadp-config.yaml" %}
{% endif %}
{% if include_lca_operator %}
{% include "group-du/lca-config.yaml" %}
{% endif %}
{% include "group-du/olm-config.yaml" %}
{% include "group-du/ptp-config.yaml" %}
{% include "group-du/sriov-operator-config-sno.yaml" %}
{% include "group-du/disable-sno-network-diag.yaml" %}
{% if setup_ztp_enable_performanceprofile %}
{% include "group-du/performance-profile-sno.yaml" %}
{% endif %}
{% endif %}
- name: "{{ group_policy_logforwarder_name }}"
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
    - path: source-crs/ClusterLogForwarder.yaml
      patches:
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
      - metadata:
          annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
            scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
            scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
            site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
            site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
        spec:
{% else +%}
      - spec:
{% endif %}
          filters:
            - name: ran-du-labels
              openshiftLabels:
                label1: test1
                label2: test2
                label3: test3
                label4: test4
          outputs:
            - kafka:
                url: tcp://10.46.55.190:9092/test
              name: kafka-output
      openapi:
        path: schema.openapi

- name: "{{ group_policy_storage_name }}"
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
  manifests:
    - path: source-crs/StorageLV.yaml
      patches:
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
      - metadata:
          annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
            scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
            scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
            site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
            site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
        spec:
{% else +%}
      - spec:
{% endif %}
          storageClassDevices:
          - storageClassName: "example-storage-class-1"
            volumeMode: Filesystem
            fsType: xfs
            devicePaths:
            - /dev/disk/by-path/pci-0000:88:00.0-nvme-1
          - storageClassName: "example-storage-class-2"
            volumeMode: Filesystem
            fsType: xfs
            devicePaths:
            - /dev/disk/by-path/pci-0000:89:00.0-nvme-1
