---
# sno-create-manifests tasks

- name: Create directories for hv-vm SNO manifests on bastion
  file:
    path: "{{ item.dir }}"
    state: directory
  delegate_to: "{{ groups['bastion'][0] }}"
  run_once: true
  when: item.enabled | default(true) | bool
  loop:
  - dir: "{{ hv_vm_manifests_directory }}/"
  - dir: "{{ hv_vm_manifests_directory }}/sno"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfigs"
    enabled: "{{ create_ai_siteconfigs }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-clusterinstances"
    enabled: "{{ create_ai_clusterinstances }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-manifests"
    enabled: "{{ create_ai_manifests }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ibi-clusterinstances"
    enabled: "{{ create_ibi_clusterinstances }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ibi-manifests"
    enabled: "{{ create_ibi_manifests }}"

- name: Symlink siteconfigs and manifests directories
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  delegate_to: "{{ groups['bastion'][0] }}"
  run_once: true
  when: item.enabled | default(true) | bool
  loop:
  - src: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfigs"
    dest: "{{ hv_vm_manifests_directory }}/sno/siteconfigs"
    enabled: "{{ create_ai_siteconfigs }}"
  - src: "{{ hv_vm_manifests_directory }}/sno/ai-manifests"
    dest: "{{ hv_vm_manifests_directory }}/sno/manifests"
    enabled: "{{ create_ai_manifests }}"

- name: Set pull-secret for bastion registry
  set_fact:
    pull_secret: "{{ disconnected_pull_secret }}"
  delegate_to: "{{ groups['bastion'][0] }}"
  run_once: true
  when: rhacm_disconnected_registry and rhacm_disconnected_registry|length > 1

# See if expanding this reduces overall timing?
- name: Template a manifest per hv-vm on bastion as a SNO
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: item.enabled | default(true) | bool
  loop:
  # AI siteconfig/clusterinstance/manifests
  - src: ai-siteconfig.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfigs/{{ inventory_hostname }}-siteconfig.yml"
    enabled: "{{ create_ai_siteconfigs }}"
  - src: ai-resources.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfigs/{{ inventory_hostname }}-resources.yml"
    enabled: "{{ create_ai_siteconfigs }}"
  - src: ai-clusterinstance.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-clusterinstances/{{ inventory_hostname }}-clusterinstance.yml"
    enabled: "{{ create_ai_clusterinstances }}"
  - src: ai-manifests.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-manifests/{{ inventory_hostname }}-manifests.yml"
    enabled: "{{ create_ai_manifests }}"

  # IBI clusterinstance / manifests
  - src: ibi-clusterinstance.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ibi-clusterinstances/{{ inventory_hostname }}-clusterinstance.yml"
    enabled: "{{ create_ibi_clusterinstances }}"
  - src: ibi-manifests.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ibi-manifests/{{ inventory_hostname }}-manifests.yml"
    enabled: "{{ create_ibi_manifests }}"
  delegate_to: "{{ groups['bastion'][0] }}"
