---
# sno-create-manifests tasks

- name: Create directories for hv-vm SNO manifests on bastion
  file:
    path: "{{ item.dir }}"
    state: directory
  when: item.enabled | default(true) | bool
  loop:
  - dir: "{{ hv_vm_manifests_directory }}/"
  - dir: "{{ hv_vm_manifests_directory }}/sno"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfig"
    enabled: "{{ create_ai_siteconfigs }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-clusterinstance"
    enabled: "{{ create_ai_clusterinstances }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-manifest"
    enabled: "{{ create_ai_manifests }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ibi-clusterinstance"
    enabled: "{{ create_ibi_clusterinstances }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ibi-manifest"
    enabled: "{{ create_ibi_manifests }}"

- name: Set pull-secret for bastion registry
  set_fact:
    pull_secret: "{{ disconnected_pull_secret }}"
  when:
  - rhacm_disconnected_registry is defined
  - rhacm_disconnected_registry is not none
  - rhacm_disconnected_registry | length > 1

- name: Template AI siteconfig manifests per SNO
  template:
    src: ai-siteconfig.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfig/{{ sno_host }}-siteconfig.yml"
  loop: "{{ groups['hv_vm'] }}"
  loop_control:
    loop_var: sno_host
  when: create_ai_siteconfigs | bool

- name: Template AI siteconfig resources per SNO
  template:
    src: ai-resources.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfig/{{ sno_host }}-resources.yml"
  loop: "{{ groups['hv_vm'] }}"
  loop_control:
    loop_var: sno_host
  when: create_ai_siteconfigs | bool

- name: Template AI clusterinstance manifests per SNO
  template:
    src: ai-clusterinstance.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-clusterinstance/{{ sno_host }}-clusterinstance.yml"
  loop: "{{ groups['hv_vm'] }}"
  loop_control:
    loop_var: sno_host
  when: create_ai_clusterinstances | bool

- name: Template AI manifests per SNO
  template:
    src: ai-manifest.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-manifest/{{ sno_host }}-manifest.yml"
  loop: "{{ groups['hv_vm'] }}"
  loop_control:
    loop_var: sno_host
  when: create_ai_manifests | bool

- name: Template IBI clusterinstance manifests per SNO
  template:
    src: ibi-clusterinstance.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ibi-clusterinstance/{{ sno_host }}-clusterinstance.yml"
  loop: "{{ groups['hv_vm'] }}"
  loop_control:
    loop_var: sno_host
  when: create_ibi_clusterinstances | bool

- name: Template IBI manifests per SNO
  template:
    src: ibi-manifest.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ibi-manifest/{{ sno_host }}-manifest.yml"
  loop: "{{ groups['hv_vm'] }}"
  loop_control:
    loop_var: sno_host
  when: create_ibi_manifests | bool
