---
apiVersion: v1
kind: Secret
metadata:
  name: seedgen
  namespace: ztp-platform-upgrade
data:
{% set _seedgen_auth = lookup('template', './seedgen-auth.j2') %}
  .dockerconfigjson: {{ (_seedgen_auth | to_json if _seedgen_auth is mapping else _seedgen_auth | trim) | b64encode }}
  seedAuth: {{ (_seedgen_auth | to_json if _seedgen_auth is mapping else _seedgen_auth | trim) | b64encode }}
