---
# ibu-generate-seed-image default vars

# The kubeconfig to the cluster being generated into a ibu seed image
seedcluster_kubeconfig: /root/ibu-ztp/seedcluster.kubeconfig

# Version of OCP we are turning into a seed image
ibu_seed_image_version: 4.15.3

recert_image: "{{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/edge-infrastructure/recert:latest"

# Bastion registry default auth
registry_user: registry
registry_password: registry
