---
# ibu-generate-seed-image default vars

# v1 for brew (stable), v1alpha1 (alpha installed operator)
seedgenerator_apiversion: v1

# Always set with a cluster you previously used as a seed cluster
seed_cluster: ""

# The kubeconfig to the cluster being generated into a ibu seed image
seedcluster_kubeconfig: "{{ install_directory }}/rhacm-ztp/ibu/seed/{{ seed_cluster }}.kubeconfig"

# Version of OCP we are turning into a seed image (The cluster should be this version already)
ibu_seed_image_version: 4.19.14

recert_image_override: false
recert_image: "{{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/edge-infrastructure/recert:latest"
