    - path: source-crs/PerformanceProfile.yaml
      patches:
      - spec:
          cpu:
            # These must be tailored for the specific hardware platform
            isolated: "2-19,22-39"
            reserved: "0-1,20-21"
          hugepages:
            defaultHugepagesSize: 1G
            pages:
              - size: 1G
                count: 32
    - path: source-crs/TunedPerformancePatch.yaml
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
      patches:
        metadata:
          annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
            scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
            scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
            site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
            site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
{% endif +%}

