    - path: source-crs/PtpConfigSlave.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
      patches:
      - metadata:
          name: du-ptp-slave
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
          annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
            scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
            scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
            site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
            site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
{% endif +%}
        spec:
          profile:
              - interface: ens5f0
                name: slave
                phc2sysOpts: -a -r -n 24
                ptp4lOpts: -2 -s --summary_interval -4
      openapi:
        path: schema.openapi

