    - path: source-crs/SriovOperatorConfig-SetSelector.yaml
      complianceType: musthave
      patches:
{%- if extraHubGroupTemplates or extraHubSiteTemplates +%}
      - metadata:
          annotations:
{%- if extraHubGroupTemplates %}
          {% raw %}
            scale-test-label-1: '{{hub fromConfigMap "" "group-template-map" "key1" hub}}'
            scale-test-label-2: '{{hub fromConfigMap "" "group-template-map" "key2" hub}}'
          {%- endraw %}
{% endif %}
{% if extraHubSiteTemplates %}
          {% raw %}
            site-test-label-1: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey1" hub}}'
            site-test-label-2: '{{hub fromConfigMap "" (printf "site-%s" .ManagedClusterName) "sitekey2" hub}}'
          {%- endraw %}
{% endif %}
{% endif +%}
      - spec:
          disableDrain: true
          configDaemonNodeSelector:
            node-role.kubernetes.io/worker: ""

