---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-core-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-core-policies
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: ztp-core-policies
spec:
  clusterSet: global
