---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztp-core-policies
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ztp-core-policies
  project: policy-app-project
  source:
    path: "{{ ztp_argocd_base_path }}/policy/telco-core"
    repoURL: http://{{ gogs_username }}:{{ gogs_password }}@{{ gogs_host }}:{{ gogs_port }}/testadmin/{{ ztp_repo_name }}.git
    targetRevision: {{ ztp_repo_branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
