---
# rhacm-siteconfig-operator tasks
# SiteConfig Operator is included with ACM 2.12

- name: Create directory for SiteConfig Operator manifests
  file:
    path: "{{ install_directory }}/rhacm-siteconfig-operator"
    state: directory

- name: Get alertmanager route for siteconfig obs annotations
  when: setup_rhacm_observability
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get route alertmanager -n open-cluster-management-observability -o jsonpath='{.spec.host}'
  register: obs_alertmanager_route

- name: Get hub cluster ID for siteconfig obs annotations
  when: setup_rhacm_observability
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get managedcluster local-cluster -o jsonpath='{.metadata.labels.clusterID}'
  register: obs_hub_cluster_id_raw

- name: Set siteconfig obs annotation facts
  when: setup_rhacm_observability
  set_fact:
    siteconfig_obs_alertmanager_route: "{{ obs_alertmanager_route.stdout }}"
    siteconfig_obs_hub_cluster_id: "{{ obs_hub_cluster_id_raw.stdout | replace('-', '') | truncate(19, True, '') }}"

- name: Template SiteConfig Operator ai-cluster templates
  when: item.enabled | default(true)
  template:
    src: ai-cluster-templates-v1.yaml.j2
    dest: "{{ install_directory }}/rhacm-siteconfig-operator/{{ item.name }}.yaml"
  loop:
  - name: "ai-cluster-templates-v1-obs"
    search: "false"
    obs: true
    enabled: "{{ setup_rhacm_observability }}"
  - name: "ai-cluster-templates-v1-search"
    search: "true"
    obs: false
  - name: "ai-cluster-templates-v1-search-obs"
    search: "true"
    obs: true
    enabled: "{{ setup_rhacm_observability }}"

- name: Template SiteConfig Operator ibi-cluster templates
  when: item.enabled | default(true)
  template:
    src: ibi-cluster-templates-v1.yaml.j2
    dest: "{{ install_directory }}/rhacm-siteconfig-operator/{{ item.name }}.yaml"
  loop:
  - name: "ibi-cluster-templates-v1-obs"
    search: "false"
    obs: true
    enabled: "{{ setup_rhacm_observability }}"
  - name: "ibi-cluster-templates-v1-search"
    search: "true"
    obs: false
  - name: "ibi-cluster-templates-v1-search-obs"
    search: "true"
    obs: true
    enabled: "{{ setup_rhacm_observability }}"

- name: Enable SiteConfig Operator
  shell: |
    export KUBECONFIG={{ hub_cluster_kubeconfig }}
    oc get mch -n open-cluster-management multiclusterhub -o json | jq '.spec.overrides.components[] |= (select(.name=="siteconfig").enabled = true)' | oc replace -f -

- name: Wait for SiteConfig Operator pod exists
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get pods -n open-cluster-management -l app.kubernetes.io/name=siteconfig-controller
  retries: 150
  delay: 2
  register: as_pod
  until: as_pod.failed == false

- name: Wait for SiteConfig Operator pod running
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get pods -n open-cluster-management -l app.kubernetes.io/name=siteconfig-controller -o jsonpath='{.items[0].status.phase}'
  retries: 150
  delay: 2
  register: as_pod
  until: as_pod.stdout == "Running"

- name: Apply SiteConfig Operator ai-cluster templates
  when: item.enabled | default(true)
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc apply -f {{ install_directory }}/rhacm-siteconfig-operator/{{ item.name }}.yaml
  loop:
  - name: "ai-cluster-templates-v1-obs"
    enabled: "{{ setup_rhacm_observability }}"
  - name: "ai-cluster-templates-v1-search"
  - name: "ai-cluster-templates-v1-search-obs"
    enabled: "{{ setup_rhacm_observability }}"

- name: Apply SiteConfig Operator ibi-cluster templates
  when: item.enabled | default(true)
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc apply -f {{ install_directory }}/rhacm-siteconfig-operator/{{ item.name }}.yaml
  loop:
  - name: "ibi-cluster-templates-v1-obs"
    enabled: "{{ setup_rhacm_observability }}"
  - name: "ibi-cluster-templates-v1-search"
  - name: "ibi-cluster-templates-v1-search-obs"
    enabled: "{{ setup_rhacm_observability }}"

- name: Patch SiteConfig Operator maxConcurrentReconciles to {{ siteconfig_max_concurrent_reconciles }}
  when: tune_sco_threads
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc patch configmap siteconfig-operator-configuration -n open-cluster-management --type=merge -p '{"data":{"maxConcurrentReconciles":"{{ siteconfig_max_concurrent_reconciles }}"}}'

- name: Restart SiteConfig Operator Pod
  when: tune_sco_threads
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc rollout restart deployment -n open-cluster-management siteconfig-controller-manager
