---
# Playbook to install Ansible Automation Platform and configure for ZTP day2 automations
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/aap-deploy.yml
#

- name: Install ansible-automation-platform
  hosts: bastion
  vars_files:
  - vars/all.yml
  roles:
  - aap-deploy
