---
# Playbook to Cleanup ACS Sensors from ACM Managed Clusters
# Note: This playbook assumes you have sensor directories in /root/secured_clusters/sensor-<cluster-name>/
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/acs-spokes-sensor-cleanup.yml
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/acs-spokes-sensor-cleanup.yml -e cleanup_sensor_generation_after_delete=true
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/acs-spokes-sensor-cleanup.yml --skip-tags registration
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/acs-spokes-sensor-cleanup.yml --skip-tags sensor-cleanup
#
- name: Cleanup ACS sensors from managed clusters
  hosts: bastion 
  connection: local
  gather_facts: true

  vars_files:
  - vars/all.yml

  vars:
    rox_api_token: "{{ lookup('env', 'ROX_API_TOKEN') }}"
    rox_central_address: "{{ lookup('env', 'ROX_CENTRAL_ADDRESS') }}"

  roles:
    - role: acs-spokes-sensor-cleanup
      tags:
        - sensor-cleanup
    - role: acs-spokes-registration
      vars:
        acs_spokes_registration_action: unregister
      tags:
        - registration
