---
# Playbook to prepare an IBI disk file and propgate that disk file to all available VM SNOs
#
# Note: This playbook runs with Jetlag's inventory so it knows all the SNO details to use
#
# Example Usage:
#
# time ansible-playbook -i ../jetlag/ansible/inventory/cloud30.local ansible/ibi-prepare-snos.yml
#

- name: Prepare an IBI disk file by preparing a single SNO for IBI
  hosts: bastion
  vars_files:
  - vars/all.yml
  roles:
  - role: ibi-create-prep-iso
    when: ibi_prepare_disk_file | default(true)
  - role: ibi-install-prep
    when: ibi_prepare_disk_file | default(true)

- name: Copy prepared IBI SNO disk file to all hypervisors
  hosts: hv
  gather_facts: false
  vars_files:
  - vars/all.yml
  roles:
  - role: ibi-copy-disk-file
    when: ibi_hv_copy_disk_file | default(true)

- name: Replace all SNO disk files with prepared IBI disk file
  hosts: hv_vm
  gather_facts: false
  vars:
    hv_ibi_disk_dir: /mnt/disk2/libvirt/ibi-disk
    seed_image_version: 4.19.14
  vars_files:
  - vars/all.yml
  tasks:
  - name: Replace each SNO's disk file with the prepared disk file
    shell: |
      cp {{ hv_ibi_disk_dir }}/prepared-{{ seed_image_version }}.qcow2 {{ hostvars[inventory_hostname]['disk_location'] }}/{{ inventory_hostname }}.qcow2
    when: ibi_replace_sno_disk_file | default(true)
