---
# Playbook to generate a seed image from an upgraded cluster
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/ibu-generate-seed-image.yml
#

- name: Generate IBU Seed Image
  hosts: bastion
  vars_files:
  - vars/all.yml
  roles:
  - ibu-generate-seed-image
