---
# Playbook to setup ZTP IBU process for RHACM
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/rhacm-ztp-ibu-setup.yml
#

- name: Setup RHACM ZTP IBU
  hosts: bastion
  vars_files:
  - vars/all.yml
  roles:
  - rhacm-ztp-ibu-setup
