---
# Playbook to create all manifests for an SNO whether AI or IBI methods
#
# Note: This playbook runs with Jetlag's inventory so it knows all the SNO details to use
#
# Example Usage:
#
# time ansible-playbook -i ../jetlag/ansible/inventory/cloud30.local ansible/sno-manifests.yml
#


- name: Create all manifest files for a SNO
  hosts: hv_vm
  gather_facts: false
  vars_files:
  - vars/all.yml
  roles:
  - sno-create-manifests
