---
# ibu-generate-seed-image tasks

- name: Create directories for IBU seed generation
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ install_directory }}/rhacm-ztp"
  - "{{ install_directory }}/rhacm-ztp/ibu"
  - "{{ install_directory }}/rhacm-ztp/ibu/seed"

- name: Template generate seed image files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0744"
  loop:
  - src: seedgen-secret.yml.j2
    dest: "{{ install_directory }}/rhacm-ztp/ibu/seed/seedgen-secret-{{ ibu_seed_image_version }}.yml"
  - src: seedimage-seedgenerator.yml.j2
    dest: "{{ install_directory }}/rhacm-ztp/ibu/seed/seedimage-seedgenerator-{{ ibu_seed_image_version }}.yml"

# ignore errors because if it does not exist, we return an error
- name: Check for existing seedgenerator
  shell: |
    KUBECONFIG={{ seedcluster_kubeconfig }} oc get seedgenerator seedimage
  ignore_errors: true
  register: get_seedgenerator

- name: Delete seedgenerator seedimage
  shell: |
    KUBECONFIG={{ seedcluster_kubeconfig }} oc delete seedgenerator seedimage
  when: get_seedgenerator.rc == 0

- name: Apply seedgen-secret to seed cluster
  shell: |
    KUBECONFIG={{ seedcluster_kubeconfig }} oc apply -f {{ install_directory }}/rhacm-ztp/ibu/seed/seedgen-secret-{{ ibu_seed_image_version }}.yml

- name: Apply seedimage-seedgenerator to seed cluster
  shell: |
    KUBECONFIG={{ seedcluster_kubeconfig }} oc apply -f {{ install_directory }}/rhacm-ztp/ibu/seed/seedimage-seedgenerator-{{ ibu_seed_image_version }}.yml

# Takes around 10 minutes to generate the seed image in the ACM/ZTP Environment
- name: Wait until seedgenerator completed
  shell: |
    KUBECONFIG={{ seedcluster_kubeconfig }} oc get seedgenerator seedimage -o json | jq -r '.status.conditions[] | select(.type=="SeedGenCompleted") | .status'
  register: seedgen_complete
  until: seedgen_complete.stdout == "True"
  retries: 240
  delay: 5
